[package]
name = "shortlink"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
nodb = "0.2"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
regex = "1.10"
